### PR TITLE
Reassign review to Katie

### PR DESCRIPTION
**Pull request by janunine**
Url is not set in the optimal way. It conflicts with testing. Please be aware that I commented out one line from app's url. Changed the homepage background, logo hover effect, and added a test on hovering.

### CODE REVIEW

**Review by ReedM99 — APPROVED** [review]
Looks neat. Thanks so much! I'll make the video.

**Review by ReedM99 — APPROVED** [review]
Second approval because of conflicting lines but fixed them.

**Review by ReedM99 — APPROVED** [review]
Third time is the charm.

**Review by ReedM99 — APPROVED** [review]
Fourth time is the charm (?)

**Review by ktracy2 — APPROVED** [review]
Looks good for Sprint 1!

**Pull request merged**
