### PR TITLE
Feat: Functional forumn page.

### PR DESCRIPTION
**Pull request by gtcolling**
Populated forum.html with Posts, which display the title of the post and the username of the author.

- Updated: Added for loops in forum.html to display the posts.
- Updated: Added hrefs in forum.html to direct the posts titles to their detailed page.
- Updated: Added a form in forum.html where users can submit posts.
- Updated: Added some styling in forum.html for the posts.
- Updated views.py to include submitting and receiving posts objects from the database.

### CODE REVIEW

**Review by ktracy2 — CHANGES_REQUESTED** [review]
Resolve conflicts before review.

**Review by ktracy2 — DISMISSED** [review]
Can be merged once db.sqlite3 file is deleted.

**Review by ktracy2 — APPROVED** [review]
Pulled onto katie-route-from-forum-to-profile and everything seems to be working fine!

**Review by SalvadorMedinaRuiz — APPROVED** [review]
Looks good to me

**Pull request merged**
