### PR TITLE
style: Improve style and add content to About page

### PR DESCRIPTION
**Pull request by ktracy2**
Improves the overall appearance of the About page.  

- I refactored about.html and added about.css to implement a CSS grid layout.  
- I also used Font Awesome icons to embellish the header and the footer to match the homepage appearance in the katie-update-layoutstyle-of-home-page branch. These embellishments to the header and footer will eventually be applied to the other html files. Specifically, I added a copyright icon on the footer, a home icon in place of the "Home" text in the header, and a "crow" icon for the logo in the header. 
- I also added content about the app and the developers.  The content is implemented using CSS grid layout in the newly added `about.css`.  The content is contained in `content-container` div, which contains `<div class = "team">`, `<div class = "description">`, and `<div class = "stack">`
 

- Will resolve Issue #60 

Screenshot (354)

### CODE REVIEW

**Review by SalvadorMedinaRuiz — APPROVED** [review]
All good here!

**Review by SalvadorMedinaRuiz — CHANGES_REQUESTED** [review]
Please fix conflicts

**Review by gtcolling — APPROVED** [review]
Looks good. Nice work!

**Review by SalvadorMedinaRuiz — APPROVED** [review]
Conflicts resolved!

**Pull request merged**
